name: Deploy GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Required permissions for actions/deploy-pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Enables Pages and provides metadata; safe to run in all builds
      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Install dependencies (Corepack + Yarn 3)
        run: |
          corepack enable
          # Ensure project Yarn version via Corepack (reads packageManager)
          corepack install
          yarn --version | xargs echo "Using Yarn version:"
          yarn --immutable

      # Build and export static site (Next.js output: 'export' writes to ./out)
      - name: Build static export
        run: |
          yarn build
          # Ensure 404.html exists for SPA deep links if Next didn't emit one
          if [ -f out/index.html ] && [ ! -f out/404.html ]; then
            cp out/index.html out/404.html
          fi

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
